spring:
  application:
    name: catalog-service
  config:
    import:
      - optional:configserver:http://config-server:8888
      - vault://
  cloud:
    vault:
      token: 934f9eae-31ff-a8ef-e1ca-4bea9e07aa09