spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mohitkaul17/config-repo.git
      vault:
        port: 8200
        host: vault
    bus:
      enabled: true
  rabbitmq:
    port: 5672
    host: rabbitmq
    addresses: "rabbitmq:5672"
    password: guest
    username: guest

server:
  port: 8888

logging:
  level:
    Root: INFO
    org.springframework: INFO
