spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mohitkaul17/config-repo
    bus:
      enabled: true

server:
  port: 8888

logging:
  level:
    Root: Error
    org.springframework: DEBUG
